image: node:14.15.4

clone:
  depth: full

definitions:
  steps:
    - step: &flow
        name: Run flow
        script:
          - yarn install --frozen-lockfile
          - yarn run flow check
    - step: &lint
        name: Run lint
        script:
          - yarn install --frozen-lockfile
          - yarn run lint
    - step: &test-unit
        name: Run unit tests
        size: 2x
        script:
          - yarn install --frozen-lockfile
          - yarn run test:unit
    - step: &test-integration
        name: Run integration tests
        size: 2x
        script:
          - yarn install --frozen-lockfile
          - yarn run test:integration-ci
    - step: &build-release-parcel
        name: Build and Release Parcel
        script:
          - pipe: docker://atlassian/artifactory-sidekick:staging
          - . .artifactory/activate.sh
          - npm set unsafe-perm true
          - yarn install --frozen-lockfile
          - yarn lerna publish from-git --no-push --yes --registry https://packages.atlassian.com/api/npm/atlassian-npm/

pipelines:
  default:
    - parallel:
        - step: *flow
        - step: *lint
        - step: *test-unit
        - step: *test-integration
  tags:
    '*':
      - parallel:
          - step: *flow
          - step: *lint
          - step: *test-unit
          - step: *test-integration
      - step: *build-release-parcel
