[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-db"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2.3.3"
napi-derive = "2"
bitflags = "*"
zerocopy = "*"
generational-arena = "*"
lazy_static = "*"
typed-arena = "*"
num-derive = "*"
num-traits = "*"

[build-dependencies]
napi-build = "1"
