[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "*"
glob-match = "0.2.1"
indexmap = "*"
pathdiff = "0.2.1"
serde = "1.0.123"
serde_json5 = "0.1.0"
